### ISSUE TITLE
Tapping twice to get to other input field

### ISSUE THREAD

**Issue by eneskaya** [MichaelCereda/react-native-form-generator#8] opened 2016-03-15 22:22 UTC
Hi @MichaelCereda 

I'm thinking of contributing to this repo. What I noticed, and what annoys me A LOT is that, when using the TextInput component, you have to tap twice on a TextInput to get to another TextInput. On first touch on another TextInput, the keyboard hides, I think in iOS it's called something like "resigning first responder", not sure though. And then on second touch, one can focus the next TextInput. 

Do you have any Idea on what the issue could be here? This is a really strange behaviour, and when you try out true native apps you won't see this.

Thanks

**Comment by MichaelCereda** [comment] 2016-03-16 18:11
First, thanks for your interest in my form generator.
this is a duplicate of https://github.com/MichaelCereda/react-native-form-generator/issues/6

please check my comments there...

i'll check this problem too in these days..

**Comment by MichaelCereda** [comment] 2016-06-14 09:02
fixed in v0.8
https://github.com/MichaelCereda/react-native-form-generator/tree/v0.8

**Closed by MichaelCereda** 2016-06-14 09:02 UTC
