### ISSUE TITLE
Suggest feature : touch form item to item.

### ISSUE THREAD

**Issue by ChangJoo-Park** [MichaelCereda/react-native-form-generator#6] opened 2016-02-29 22:21 UTC
Hello @MichaelCereda.
I use react-native-form-generator,

in your example, an inputfield to another inputfield situation.
![touch](https://cloud.githubusercontent.com/assets/107390/12499709/edc1c298-c07a-11e5-916c-394de83ebe51.gif)

first inputfiield touch -> touch somewhere for hide keyboard -> second touch inputfield

how to remove unnecessary hide keyboard action?

**Comment by MichaelCereda** [comment] 2016-02-29 22:59
Do you mean how to hide and focus the field with just one touch?

**Comment by MichaelCereda** [comment] 2016-02-29 23:32
I personally think that it's related to keyboardDismissMode='interactive', it that mode the keyboard listens for an events.... 

https://github.com/MichaelCereda/react-native-form-generator/blob/master/lib/KeyboardAwareScrollView.js#L63

I'll investigate

**Comment by ChangJoo-Park** [comment] 2016-02-29 23:42
thank you. @MichaelCereda 

I'll investigate too.

I think just one clicking for field to field(with  keyboard opened)  will be more nicer

**Comment by eneskaya** [comment] 2016-03-20 12:06
@MichaelCereda tried to change the keyboardDismissMode to 'none' and 'on-drag', didn't change a thing :/ But it is in fact the ScrollView. When using normal View this behaviour disappears and you can tap directly in to InputFields.

**Comment by 5amfung** [comment] 2016-03-24 10:30
This is how I solved the problem by using a different keyboard aware view and adding keyboardShouldPersisTaps.

https://github.com/APSL/react-native-keyboard-aware-scroll-view

```
<KeyboardAwareScrollView ref='keyboardAwareScrollView' keyboardShouldPersistTaps={true}>
...
</KeyboardAwareScrollView>    

```

**Comment by eneskaya** [comment] 2016-03-24 13:28
@5amfung Nice! That solves it very well. Thank you.

**Comment by MichaelCereda** [comment] 2016-03-24 13:30
Oh.. that's cool .. i actually tried keyboardShouldPersistTaps={true} but it didn't work with my version of KeyboardAwareScrollView .. i'm going to check that repo and if everything works i'm going to use it in this project.
Thanks!

**Comment by MichaelCereda** [comment] 2016-03-31 11:15
It works but not very well, at least after my tests.. 
i need to do a mashup between the two to create something customizable and 100% working at the same time.

**Comment by MichaelCereda** [comment] 2016-06-14 09:01
Fixed in Branch v0.8 https://github.com/MichaelCereda/react-native-form-generator/tree/v0.8

It was mainly caused by a bug of react

**Comment by MichaelCereda** [comment] 2016-06-15 05:09
A new version of the docs is coming and it will include that feature

**Closed by MichaelCereda** 2016-06-15 05:09 UTC

**Comment by jesouhaite08** [comment] 2016-12-31 02:20
I'm having this issue. Wasn't this fixed?
